### ISSUE TITLE
Parameterizing On a Test Plan will not open a pop-up with the option to edit the parameter

### ISSUE THREAD

**Issue by apantir** [StefanHolst/opentap-tui#90] opened 2022-09-28 06:54 UTC
**Environment**

Windows 10, 64-bit
OpenTAP v9.19.0+22538968
TUI 1.0.0-rc+cfb8eede

**Steps to reproduce:**

* 1. Add a **Delay** step
* 2. Go to **F7 Settings** panel
* 3. **Parameterize On Test Plan** the **Time Delay** option 
* 4. Edit the parameter

**Actual result:**

After parameterezation you can not edit only and you need to unparameterize > edit > parameterize again

**Notes**

When using the option **F1 Parameterize** a pop-up will opent but still can not edit the parameter after saving

**Comment by rmadsen-ks** [comment] 2022-10-17 11:29
It seems we are lacking a hotkey for edit parameter

**Comment by frederikja163** [comment] 2022-10-27 10:06
Closing this as its intended behaviour. To edit a parameter you need to visit the place where the property is parameterized to. In this case the TestPlan

**Closed by frederikja163** 2022-10-27 10:06 UTC
