### ISSUE TITLE
Exception thrown when clicking AssignOutput and no outputs are available.

### ISSUE THREAD

**Issue by StefanHolst** [StefanHolst/opentap-tui#11] opened 2022-03-07 14:48 UTC
Originally filed October 19 2021 by Rolf Madsen on [GitLab](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/-/issues/89)

**Stack trace:**

```
2021-10-19 09:47:04.538428 ; tui            ; Debug       ; Exception: Object reference not set to an instance of an object.
2021-10-19 09:47:04.538778 ; tui            ; Debug       ;     at OpenTap.TestStepExtensions.GetFormattedName(ITestStep step) in /home/romadsen/code/opentap/Engine/TestStep.cs:line 1130
2021-10-19 09:47:04.538785 ; tui            ; Debug       ;     at OpenTap.AssignOutputDialog.SelectedOutputItem.ToString() in /home/romadsen/code/opentap/Engine/AssignOutputDialog.cs:line 53
2021-10-19 09:47:04.538789 ; tui            ; Debug       ;     at OpenTap.Tui.Views.PropertiesView.<>c__DisplayClass36_0.<.ctor>b__0(Object item)
2021-10-19 09:47:04.538792 ; tui            ; Debug       ;     at OpenTap.Tui.TreeView.SetTreeViewSource[T](List`1 items)
2021-10-19 09:47:04.538798 ; tui            ; Debug       ;     at OpenTap.Tui.TuiUserInput.RequestUserInput(Object dataObject, TimeSpan Timeout, Boolean modal)
2021-10-19 09:47:04.538802 ; tui            ; Debug       ;     at OpenTap.UserInput.Request(Object dataObject, Boolean modal) in /home/romadsen/code/opentap/Engine/UserInput.cs:line 32
2021-10-19 09:47:04.538805 ; tui            ; Debug       ;     at OpenTap.TestStepMenuModel.ControlUsingOutput() in /home/romadsen/code/opentap/Engine/ParametersMenuModel.cs:line 154
2021-10-19 09:47:04.538809 ; tui            ; Debug       ;     at OpenTap.DefaultDataAnnotator.MethodAnnotation.Invoke() in /home/romadsen/code/opentap/Engine/Annotations/Annotation.cs:line 1627
2021-10-19 09:47:04.538813 ; tui            ; Debug       ;     at OpenTap.Tui.Views.PropertiesView.<>c__DisplayClass29_0.<buildMenuItems>b__0()
2021-10-19 09:47:04.539150 ; tui            ; Debug       ; Exception caught at:
2021-10-19 09:47:04.539177 ; tui            ; Debug       ;     at Void <buildMenuItems>b__0()
2021-10-19 09:47:04.539182 ; tui            ; Debug       ;     at Boolean ProcessKey(Terminal.Gui.KeyEvent)
2021-10-19 09:47:04.539185 ; tui            ; Debug       ;     at Boolean ProcessKey(Terminal.Gui.KeyEvent)
2021-10-19 09:47:04.539190 ; tui            ; Debug       ;     at Boolean ProcessKey(Terminal.Gui.KeyEvent)
2021-10-19 09:47:04.539192 ; tui            ; Debug       ;     ...
```

**Comment by frederikja163** [comment] 2022-08-22 14:01
Closing as I'm unable to reproduce this on main.

**Closed by frederikja163** 2022-08-22 14:01 UTC
Labels: Usability
