### ISSUE TITLE
You have access to Test Plan Settings using F1 without having a step added

### ISSUE THREAD

**Issue by apantir** [StefanHolst/opentap-tui#98] opened 2022-10-06 11:42 UTC
**Environment**

macOS v12.6, 64-bit
OpenTAP v9.19.0+22538968
TUI 1.0.0-rc+cfb8eede

**Steps to reproduce:**

* 1. Open TUI
* 2. Press **F1**
* 3. Test Plan Settings is available
* 4. Edit the name

**Actual result:**

After you try to edit the Name in Test Plan Settings and press the key ENTER it will get out from Test Plan Settings

![2022-10-06 13 43 19](https://user-images.githubusercontent.com/110477118/194304347-eba4a4fe-6359-4349-b6fb-0a0a2a9a2576.gif)

**Expected result:**

You should not be able to enter in edit mode if you don´t have a step added in Test Plan

**Comment by rmadsen-ks** [comment] 2022-10-17 07:33
This is a very minor usability issue. I recommend not fixing it.

**Comment by frederikja163** [comment] 2022-10-17 08:51
The issue is the other way around. You should be able to access the settings, but for some reason the button is not showing up.

**Comment by frederikja163** [comment] 2022-10-27 12:41
Closing this as its intended behaviour

**Closed by frederikja163** 2022-10-27 12:41 UTC
Labels: Usability
