### ISSUE TITLE
TUI crashes when checking and unchecking the Break Conditions option

### ISSUE THREAD

**Issue by apantir** [StefanHolst/opentap-tui#86] opened 2022-09-27 20:50 UTC
**Environment**

Windows 10, 64-bit
OpenTAP v9.19.0+22538968
TUI 1.0.0-rc+cfb8eede

**Steps to reproduce:**

* 1. Add a **Delay** step
* 2. Go to F7 Step settings
* 3. Access **Common / Break Conditions**
* 4. Check the option and hit **ESC** key
* 5. Access it again and uncheck it
* 6. Press **ESC** and after, left directional key

**Actual result:**

TUI crashes.

**Additional info**

If the crush didn't happened, check and uncheck until the app will crush.

**Comment by frederikja163** [comment] 2022-10-17 07:42
Cannot reproduce this. Can you test using the newest version of the TUI, if it still crashes for you, providing the session logs would be extremely helpful.

(Might be related to #72 )

**Comment by frederikja163** [comment] 2022-11-21 08:17
Closing as i cannot reproduce

**Closed** 2022-11-21 08:17 UTC
Labels: bug
